
markdown: rdiscount
highlighter: pygments

permalink: /:title

title: FlamingPeach
url: http://flaming-peach.github.io
feed: /atom.xml  
author_info: <a href="http://flaming-peach.github.io/">FlamingPeach</a>
